// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DataDefine.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_DATADEFINE_H_
#define _FAST_DDS_GENERATED_DATADEFINE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DATADEFINE_SOURCE)
#define DATADEFINE_DllAPI __declspec( dllexport )
#else
#define DATADEFINE_DllAPI __declspec( dllimport )
#endif // DATADEFINE_SOURCE
#else
#define DATADEFINE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DATADEFINE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure Target defined by the user in the IDL file.
 * @ingroup DataDefine
 */
class Target
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Target();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Target();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target(
            const Target& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target(
            Target&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target& operator =(
            const Target& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target& operator =(
            Target&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Target object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Target& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Target object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Target& x) const;

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index);

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const;

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index();


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message();

private:

    uint32_t m_index{0};
    std::string m_message;

};


/*!
 * @brief This class represents the structure ReplyInfo defined by the user in the IDL file.
 * @ingroup DataDefine
 */
class ReplyInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ReplyInfo();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ReplyInfo();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ReplyInfo that will be copied.
     */
    eProsima_user_DllExport ReplyInfo(
            const ReplyInfo& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ReplyInfo that will be copied.
     */
    eProsima_user_DllExport ReplyInfo(
            ReplyInfo&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ReplyInfo that will be copied.
     */
    eProsima_user_DllExport ReplyInfo& operator =(
            const ReplyInfo& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ReplyInfo that will be copied.
     */
    eProsima_user_DllExport ReplyInfo& operator =(
            ReplyInfo&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x ReplyInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ReplyInfo& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ReplyInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ReplyInfo& x) const;

    /*!
     * @brief This function sets a value in member is_recved
     * @param _is_recved New value for member is_recved
     */
    eProsima_user_DllExport void is_recved(
            uint8_t _is_recved);

    /*!
     * @brief This function returns the value of member is_recved
     * @return Value of member is_recved
     */
    eProsima_user_DllExport uint8_t is_recved() const;

    /*!
     * @brief This function returns a reference to member is_recved
     * @return Reference to member is_recved
     */
    eProsima_user_DllExport uint8_t& is_recved();

private:

    uint8_t m_is_recved{0};

};


/*!
 * @brief This class represents the structure RestartInfo defined by the user in the IDL file.
 * @ingroup DataDefine
 */
class RestartInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport RestartInfo();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~RestartInfo();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object RestartInfo that will be copied.
     */
    eProsima_user_DllExport RestartInfo(
            const RestartInfo& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object RestartInfo that will be copied.
     */
    eProsima_user_DllExport RestartInfo(
            RestartInfo&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object RestartInfo that will be copied.
     */
    eProsima_user_DllExport RestartInfo& operator =(
            const RestartInfo& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object RestartInfo that will be copied.
     */
    eProsima_user_DllExport RestartInfo& operator =(
            RestartInfo&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x RestartInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const RestartInfo& x) const;

    /*!
     * @brief Comparison operator.
     * @param x RestartInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const RestartInfo& x) const;

    /*!
     * @brief This function sets a value in member participant
     * @param _participant New value for member participant
     */
    eProsima_user_DllExport void participant(
            uint8_t _participant);

    /*!
     * @brief This function returns the value of member participant
     * @return Value of member participant
     */
    eProsima_user_DllExport uint8_t participant() const;

    /*!
     * @brief This function returns a reference to member participant
     * @return Reference to member participant
     */
    eProsima_user_DllExport uint8_t& participant();


    /*!
     * @brief This function sets a value in member transportType
     * @param _transportType New value for member transportType
     */
    eProsima_user_DllExport void transportType(
            uint8_t _transportType);

    /*!
     * @brief This function returns the value of member transportType
     * @return Value of member transportType
     */
    eProsima_user_DllExport uint8_t transportType() const;

    /*!
     * @brief This function returns a reference to member transportType
     * @return Reference to member transportType
     */
    eProsima_user_DllExport uint8_t& transportType();

private:

    uint8_t m_participant{0};
    uint8_t m_transportType{0};

};

#endif // _FAST_DDS_GENERATED_DATADEFINE_H_



